export const ACTION_TYPE = {
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    DECREASE_QUANTITY:"DECREASE_QUANTITY",

    ADD_TO_WISHLIST:"ADD_TO_WISHLIST",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",

    AUTH_REQUEST: "AUTH_REQUEST",
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",
    LOGOUT: "LOGOUT",
    FORGET_PASSWORD: "FORGET_PASSWORD",
    FAILURE: "FAILURE"

}